### ISSUE TITLE
Controller App\Controllers\HomeController not found

### ISSUE THREAD

**Issue by AlifJamain** [Bulveyz/router-php#1]
Controller App\Controllers\HomeController not found

How to solve this problem?

**Comment by F4brizio** [comment]
I have exactly the same problem, did you manage to fix it?

**Comment by AlifJamain** [comment]
not yet... but I found new php routes...

**Comment by F4brizio** [comment]
In my case, I had that problem when I uploaded it to production, but I fixed it by adding the classmap in composer.json.

```
{
...
    "autoload": {
        "psr-4": {
            "App\\": "app"
        },
        "classmap": [
            "App/"
        ],
        "files": [
            "App/helpers.php"
        ]
    },
...
}
```
In case it serves to someone.
